### ISSUE TITLE
Create Entity and DAO classes

### ISSUE THREAD

**Issue by hmanchev** [alexanderpanayotov/CSS-generate#3]
Description:
Create entity and dao for saving CSS style. 

Needed field:
1. CSS style - string
2. Type - string
3. Name - string

To be implemented methods for: 
1. Save new style - 5 maximum from one category. Must check how many styles are stored from the given category.
2. List all styles
3. List style by type (category)

Assign: Martin
Estimation: 24 Nov

**Comment by simeonvasilev** [comment]
Готово
